<TuringGrid>:
    GridLayout:
        cols: 1
        size: root.width, root.height/4
        GridLayout:
            cols: 3

            Button:
                text: "Zmien alfabet"
                on_press: root.change_alphabet()

            Button:
                text: "Zmien stany"
                on_press: root.change_state_list()

            Button:
                text: "Zmien diagramy"
                on_press: root.change_state_diagram()